/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
id INT NOT NULL,
	name VARCHAR(50) NOT NULL,
	data_of_birth DATE NOT NULL,
	escape_attempts INT,
	neutered BOOL,
	weight_kg DECIMAL
);

ALTER TABLE animals
ADD species text;

CREATE TABLE owners (
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	full_name VARCHAR(75) NOT NULL,
	age INT,
	PRIMARY KEY(id)
);

CREATE TABLE species (
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(75) NOT NULL,
	PRIMARY KEY(id)
);

ALTER TABLE animals
DROP COLUMN id;
ADD COLUMN id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY;

ALTER TABLE animals
DROP species


BEGIN TRANSACTION;
ALTER TABLE animals
ADD COLUMN species_id INT;
ALTER TABLE animals
ADD FOREIGN KEY(species_id)
REFERENCES species(id)
COMMIT TRANSACTION

BEGIN TRANSACTION;
ALTER TABLE animals
ADD COLUMN owner_id INT;
ALTER TABLE animals
ADD CONSTRAINT owner_id
FOREIGN KEY(owner_id)
REFERENCES owners(id);
COMMIT TRANSACTION
